In [1]:
import os
import pathlib
import numpy as np
import cv2 
import matplotlib as mpl

In [2]:
def to_homo_coords(coords):
    return np.array([
        [point[0], point[1], 1.]
        for point in coords
    ], dtype=np.float32)

def from_homo_coords(coords):
    return np.array([
        [point[0] / point[2], point[1] / point[2]]
        for point in coords
    ])

In [3]:
src = np.array([
    [79., 103.],
    [166., 67.],
    [425., 434.],
    [701., 228.]
], dtype=np.float32)

dst = np.array([
    [0., 0.],
    [343., 0.],
    [0., 557.],
    [343., 557.]
], dtype=np.float32)

M = cv2.getPerspectiveTransform(src, dst)
M

array([[-4.72455375e+01,  4.93865739e+01, -1.35441965e+03],
       [-4.07932908e+01, -9.85837860e+01,  1.33767999e+04],
       [-5.03697922e-02, -1.46352343e-01,  1.00000000e+00]])

In [4]:
rectangle1 = np.array([
    [161., 83.],
    [175., 83.],
    [161., 94.],
    [175., 94.]
], dtype=np.float32)

rectangle2 = np.array( [
    [448., 140.],
    [472., 140.],
    [448., 169.],
    [472., 169.]
], dtype=np.float32)

In [5]:
cv2.warpPerspective(rectangle2, M, rectangle2.shape) # ??? 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [6]:
hrec = to_homo_coords(rectangle2)
res = from_homo_coords((M @ hrec.T).T)
res

array([[371.09266394, 444.66357461],
       [386.93239932, 454.86830883],
       [306.14104591, 465.65055491],
       [322.21844817, 474.40960367]])

In [7]:
hrec = to_homo_coords(rectangle2)
hrec

array([[448., 140.,   1.],
       [472., 140.,   1.],
       [448., 169.,   1.],
       [472., 169.,   1.]], dtype=float32)

In [10]:
rectangle2 = np.array( [[
    [448., 140.],
    [472., 140.],
    [448., 169.],
    [472., 169.]
]], dtype=np.float32)
cv2.perspectiveTransform(rectangle2, M)

array([[[371.09265, 444.66357],
        [386.9324 , 454.86832],
        [306.14105, 465.65054],
        [322.21844, 474.4096 ]]], dtype=float32)